# Makefile for net programs
CXX = g++
LIBS = -lpthread -lrt -libverbs -lrdmacm
CFLAGS = -O2 -DRDMA

PROGS = nsdperf_rdma

all: $(PROGS)

clean:
	rm -f $(PROGS)

$(PROGS): nsdperf.C
	$(CXX) $(CFLAGS) -o $@ nsdperf.C $(LIBS)
